version: "3"
services:      
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        container_name: register-product-db
        networks:
          - api
        ports:
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: register-product-db
    client:
        image: felipecouto00/register-product-frontend:latest
        container_name: register-product-frontend
        extra_hosts:
          - "host.docker.internal:host-gateway"
        networks:
          - api
        ports:
            - "3030:3030"

    api:
        image: felipecouto00/register-product-backend:latest
        container_name: register-product-backend
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
          - api
        ports:
            - "3001:3001"
        environment: 
            - JWT_SECRET=claranet
        depends_on:
            - db
networks:
  api: