version: "3"
services:      
    register-product-db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        container_name: register-product-db        
        ports:
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: register-product-db